website/web/router.ex
defmodule Portal.Router do
  use Portal.Web, :router
  import Portal.Permissions

  defp assign_if_in_session(conn, key) do
    if conn.assigns[key] do
      conn
    else
      val = get_session(conn, key)
      if val do
        assign conn, key, val
      else
        conn
      end
    end
  end

  defp get_locale(%{params: %{"locale" => locale}}), do: locale
  defp get_locale(%{cookies: %{"locale" => locale}}), do: locale
  defp get_locale(conn) do
    case get_req_header(conn, "accept-language") do
      ["fr" <> _] -> "fr"
      _ -> nil
    end
  end

  defp fetch_locale(conn, _) do
    locale = get_locale(conn)
    if locale do
      Gettext.put_locale Portal.Gettext, locale
      put_session conn, :locale, locale
    else
      conn
    end
  end

  defp remember_locale(%{params: %{"locale" => locale}} = conn, _) do
    put_resp_cookie conn, "locale", locale
  end
  defp remember_locale(conn, _), do: conn

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_locale
    plug :remember_locale
    plug :assign_if_in_session, :current_user
    plug :assign_if_in_session, :locale
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_if_in_session, :current_user
  end

  defp full_path(conn) do
    URI.to_string %URI{path: conn.request_path, query: conn.query_string}
  end

  defp authenticate(conn, _) do
    if conn.assigns[:current_user] do
      conn
    else
      conn
        |> put_session(:redirect_to, full_path(conn))
        |> redirect(to: "/login")
        |> halt
    end
  end

  pipeline :authenticated do
    plug :authenticate
  end

  defp is_staff_user(conn, _) do
    if is_staff_user?(conn) do
      conn
    else
      conn
        |> put_status(404)
        |> render(Portal.ErrorView, "404.html")
        |> halt
    end
  end

  pipeline :staff do
    plug :is_staff_user
  end

  defp is_superuser(conn, _) do
    if Portal.Permissions.is_superuser?(conn) do
      conn
    else
      conn
        |> put_status(404)
        |> render(Portal.ErrorView, "404.html")
        |> halt
    end
  end

  pipeline :superuser do
    plug :is_superuser
  end

  scope "/", Portal do
    pipe_through :browser

    get       "/",        PageController, :index
    get       "/login",   SessionController, :new
    post      "/login",   SessionController, :create
  end

  scope "/", Portal do
    pipe_through [:browser, :authenticated]

    get       "/account",     SessionController, :about
    resources "/allocations", AllocationController, only: [:index, :show]
    resources "/jobs/niagara", JobController, only: [:index, :show]
    resources "/jobs/mist",    MistjobController, only: [:index, :show]
    post      "/logout",      SessionController, :delete
    resources "/storage",     StorageController, only: [:index, :show]
    get "/storage/:group/:filesystem", StorageController, :breakdown
  end

  scope "/", Portal do
    pipe_through [:browser, :authenticated, :staff]

    resources "/users", UserController, only: [:index, :show]
    resources "/groups", GroupController, only: [:show]
  end

  scope "/", Portal do
    pipe_through [:browser, :authenticated, :superuser]

    get "/testjobs",                  TestjobController, :index
    get "/testjobs/niagara/average",  TestjobController, :average
    get "/testjobs/niagara/node/:id", TestjobController, :node
    get "/testjobs/niagara/week/:id", TestjobController, :week
  end

  scope "/api/v1", Portal do
    pipe_through [:api, :authenticated]

    get "/jobs/niagara/:jobid/utilization.tsv", ApiController, :utilization
  end
end

website/web/views/layout_view.ex
defmodule Portal.LayoutView do
  use Portal.Web, :view

  def full_path_with_locale(conn, locale) do
    q = URI.decode_query conn.query_string
    q = Map.put q, "locale", locale
    URI.to_string %URI{path: conn.request_path, query: URI.encode_query(q)}
  end
end

website/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <% myscinet = gettext("my.SciNet") %>
    <title><%= myscinet %></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/portal.css") %>">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> 
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand logo" href="/"><%= myscinet %></a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% nav = @conn.assigns[:nav] %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gettext "Jobs" %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li class="<%= if nav == "jobs", do: "active" %>">
                    <a href="<%= job_path @conn, :index %>"><%= gettext "Niagara" %></a>
                  </li>
                  <li class="<%= if nav == "mistjobs", do: "active" %>">
                    <a href="<%= mistjob_path @conn, :index %>"><%= gettext "Mist" %></a>
                  </li>
                </ul>
              </li>
              <li class="<%= if nav == "allocations", do: "active" %>">
                <a href="<%= allocation_path @conn, :index %>"><%= gettext "Allocations" %></a>
              </li>
              <li class="<%= if nav == "storage", do: "active" %>">
                <a href="<%= storage_path @conn, :index %>"><%= gettext "Storage" %></a>
              </li>
              <li class="<%= if nav == "account", do: "active" %>">
                <a href="<%= session_path @conn, :about %>"><%= gettext "Account" %></a>
              </li>
              <%= if is_staff_user?(@conn) do %>
              <li class="<%= if nav == "users", do: "active" %>">
                <a href="<%= user_path @conn, :index %>"><%= gettext "Users" %></a>
              </li>
              <% end %>
              <%= if is_superuser?(@conn) do %>
              <li class="<%= if nav == "testjobs", do: "active" %>">
                <a href="<%= testjob_path @conn, :index %>">TestJobs</a>
              </li>
              <% end %>
            </ul>
            <%= if @conn.assigns[:current_user] do %>
            <%= form_for @conn, session_path(@conn, :delete), [as: :session, class: "navbar-form navbar-right"], fn _f -> %>
              <%= submit gettext("Sign out ") <> @current_user.username, class: "btn btn-default" %>
            <% end %>
            <% else %>
            <form action="/login" class="navbar-form navbar-right">
              <button type="submit" class="btn btn-default"><%= gettext "Sign in" %></button>
            </form>
            <% end %>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= if @conn.assigns[:locale] == "fr" do %>
                <a href="<%= full_path_with_locale(@conn, "en") %>">EN</a>
                <% else %>
                <a href="<%= full_path_with_locale(@conn, "fr") %>">FR</a>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div id="errmsgs"></div>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
  </body>
</html>