website/web/router.ex
defmodule Portal.Router do
  use Portal.Web, :router
  import Portal.Permissions

  defp assign_if_in_session(conn, key) do
    if conn.assigns[key] do
      conn
    else
      val = get_session(conn, key)
      if val do
        assign conn, key, val
      else
        conn
      end
    end
  end

  defp get_locale(%{params: %{"locale" => locale}}), do: locale
  defp get_locale(%{cookies: %{"locale" => locale}}), do: locale
  defp get_locale(conn) do
    case get_req_header(conn, "accept-language") do
      ["fr" <> _] -> "fr"
      _ -> nil
    end
  end

  defp fetch_locale(conn, _) do
    locale = get_locale(conn)
    if locale do
      Gettext.put_locale Portal.Gettext, locale
      put_session conn, :locale, locale
    else
      conn
    end
  end

  defp remember_locale(%{params: %{"locale" => locale}} = conn, _) do
    put_resp_cookie conn, "locale", locale
  end
  defp remember_locale(conn, _), do: conn

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_locale
    plug :remember_locale
    plug :assign_if_in_session, :current_user
    plug :assign_if_in_session, :locale
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_if_in_session, :current_user
  end

  defp full_path(conn) do
    URI.to_string %URI{path: conn.request_path, query: conn.query_string}
  end

  defp authenticate(conn, _) do
    if conn.assigns[:current_user] do
      conn
    else
      conn
        |> put_session(:redirect_to, full_path(conn))
        |> redirect(to: "/login")
        |> halt
    end
  end

  pipeline :authenticated do
    plug :authenticate
  end

  defp is_staff_user(conn, _) do
    if is_staff_user?(conn) do
      conn
    else
      conn
        |> put_status(404)
        |> render(Portal.ErrorView, "404.html")
        |> halt
    end
  end

  pipeline :staff do
    plug :is_staff_user
  end

  defp is_superuser(conn, _) do
    if Portal.Permissions.is_superuser?(conn) do
      conn
    else
      conn
        |> put_status(404)
        |> render(Portal.ErrorView, "404.html")
        |> halt
    end
  end

  pipeline :superuser do
    plug :is_superuser
  end

  scope "/", Portal do
    pipe_through :browser

    get       "/",        PageController, :index
    get       "/login",   SessionController, :new
    post      "/login",   SessionController, :create
  end

  scope "/", Portal do
    pipe_through [:browser, :authenticated]

    get       "/account",     SessionController, :about
    resources "/allocations", AllocationController, only: [:index, :show]
    resources "/jobs/niagara", JobController, only: [:index, :show]
    resources "/jobs/mist",    MistjobController, only: [:index, :show]
    post      "/logout",      SessionController, :delete
    resources "/storage",     StorageController, only: [:index, :show]
    get "/storage/:group/:filesystem", StorageController, :breakdown
  end

  scope "/", Portal do
    pipe_through [:browser, :authenticated, :staff]

    resources "/users", UserController, only: [:index, :show]
    resources "/groups", GroupController, only: [:show]
  end

  scope "/", Portal do
    pipe_through [:browser, :authenticated, :superuser]

    get "/testjobs",                  TestjobController, :index
    get "/testjobs/niagara/average",  TestjobController, :average
    get "/testjobs/niagara/node/:id", TestjobController, :node
    get "/testjobs/niagara/week/:id", TestjobController, :week
  end

  scope "/api/v1", Portal do
    pipe_through [:api, :authenticated]

    get "/jobs/niagara/:jobid/utilization.tsv", ApiController, :utilization
  end
end

website/web/controllers/user_controller.ex
defmodule Portal.UserController do
  use Portal.Web, :controller
  require Portal.LDAP
  require Portal.Storage
  import Ecto.Query

  plug :setnav

  defp setnav(conn, _) do
    assign conn, :nav, "users"
  end

  def index(conn, %{"q" => q}) do
    users = Portal.LDAP.user_search(q)
    conn
      |> assign(:users, users)
      |> render("index.html")
  end
  def index(conn, _), do: render conn, "index.html"

  def show(conn, %{"id" => id}) do

    try do
        info = Portal.LDAP.user_info(id)

        query = Portal.Jobsum
          |> where(username: ^id)
          |> limit(10)
          |> order_by(desc: :endtime)
          |> select([:account, :elapsed, :endtime, :jobid, :jobname, :nnodes, :username, :state])
        jobs = Portal.Repo.all(query)

        allocations = Portal.Allocation.get_accounts_for_user(id)

        storage = Portal.Storage.storage_for_user(id)

        conn
          |> assign(:user, info)
          |> assign(:jobs, jobs)
          |> assign(:allocations, allocations)
          |> assign(:storage, storage)
          |> render("show.html")
    rescue
        _ -> render(conn, Portal.ErrorView, "404.html")
    end
  end

end

website/web/views/user_view.ex
defmodule Portal.UserView do
  use Portal.Web, :view
end

website/web/templates/user/index.html.eex
<% q = @conn.query_params["q"] %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form action="<%= user_path @conn, :index %>">
      <div class="form-group">
        <div class="input-group">
          <input type="search" name="q" class="form-control"
            placeholder="<%= gettext "Search for users..." %>"
            <%= if q, do: "value=#{q}", else: "" %>>
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><%= gettext "Search" %></button>
          </span>
        </div>
      </div>
    </form>
  </div>
</div>

<%= if @conn.assigns[:users] do %>
<table class="table table-hover">
  <thead>
    <th><%= gettext "User" %></th>
    <th><%= gettext "Name" %></th>
    <th><%= gettext "Email" %></th>
  </thead>
  <tbody>
  <%= for user <- Enum.sort_by(@users, &(&1.cn)) do %>
    <tr>
      <td>
      <% username = hd(user.uid) %>
      <a href="<%= user_path @conn, :show, username %>"><%= username %></a>
      </td>
      <td style="vertical-align:middle"><%= user.cn %></td>
      <td style="vertical-align:middle"><%= Enum.join(user.mail, ", ") %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

website/web/templates/user/show.html.eex
<h3><%= gettext "User" %> <%= @user.username %></h3>

<dl class="dl-horizontal">

<dt><%= gettext "Full name" %></dt>
<dd><%= @user.fullname %></dd>

<dt><%= gettext "Email addresses" %></dt>
<dd><%= Enum.join(@user.emails, ", ") %></dd>

<dt><%= gettext "Groups" %></dt>
<dd>
<a href="<%= group_path @conn, :show, hd(@user.groups) %>"><%= hd(@user.groups) %></a><%=
    for g <- tl @user.groups do %>, <a href="<%= group_path @conn, :show, g %>"><%= g %></a><% end %>
</dd>

<dt><%= gettext "Allocations" %></dt>
<dd>
<a href="<%= allocation_path @conn, :show, hd(@allocations) %>"><%= hd(@allocations) %></a><%=
    for a <- tl @allocations do %>, <a href="<%= allocation_path @conn, :show, a %>"><%= a %></a><% end %>
</dd>

</dl>

<h4><%= gettext "Storage" %></h4>
<%= render Portal.StorageView, "table.html", conn: @conn, group: nil, groups: nil, storage: @storage, links: nil %>

<h4><%= gettext "Recent Jobs" %></h4>
<%= if @conn.assigns[:jobs] do %>
<%= render Portal.JobView, "_jobs.html", conn: @conn, jobs: @jobs, locale: get_locale(@conn) %>
<% end %>

<p>
<a href="<%= job_path @conn, :index, user: @user.username %>"><%= gettext "More..." %></a>
</p>